services:
  - type: web
    name: neo-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_TYPE
        value: postgres
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
